### ISSUE TITLE
Program to big

### ISSUE THREAD

**Issue by KeenVox** [Jacajack/usynth#1]
Hi there,

I just built your nice project but while compiling I get the message:

Program:   35206 bytes (107.4% Full)

and while flashing to the atmega I get:

ERROR: section ".text" does not fit into "flash" memory:
    0x0 + 35174 > 32768

Am I doing something wrong? Hope you can help. Would love to test this litte synth :-)

Best wishes 
Keen

**Comment by jpnielsen** [comment]
my attempt at a workaround

I got this:
```
make 
...
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: usynth.elf section `.text' will not fit in region `text'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: region `text' overflowed by 2438 bytes
collect2: error: ld returned 1 exit status
```

in src/makefile, line 11, CFLAGS.

Change -O3 to -Os and save the file. (see [GCC docs](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) )

after:

```
make
...
avr-size -C --mcu=atmega328p usynth.elf
AVR Memory Usage
----------------
Device: atmega328p
Program: 28056 bytes (85.6% Full)
(.text + .data + .bootloader)
Data: 1578 bytes (77.1% Full)
(.data + .bss + .noinit)
EEPROM: 699 bytes (68.3% Full)
(.eeprom)
```

I haven't flashed and tested - let me know if it works.

**Comment by KeenVox** [comment]
It worked perfectly! Thank you so much !!

**Comment by Jacajack** [comment]
Hi,

What version of GCC are you using? I noticed that the newer versions produce significantly larger binaries. The performance seems to be a bit worse too. For this reason I stick with older compiler versions when compiling the usynth code. Last time I checked, GCC 10.1.0 seemed to be good enough. By the way, you can find precompiled binaries [here](https://github.com/Jacajack/usynth/tree/master/bin).

Optimizing the code for size is obviously a good workaround to get the code into the flash, but you may find the performance unsatisfactory. It's not bound to happen, of course, but is likely. When that happens, the sound appears distorted in a distinctive manner. You might miss it at first, but once you hear the clean version it becomes obvious. 

The way I debugged performance issues in the code is actually very simple. MIDI controller 111 controls "profiling" of a certain load balancing channel (one of the 21 paths of execution in the main switch statement). If there's still some time left after generating the sample, the green LED will light up. Brightness of the LED tells you how much spare time you have in each branch. When the LED is visibly flickering, it usually means that this branch is overloaded and some artifacts may be audible.

I have no idea how this happened, but somehow I have unsubscribed from the notifications from this repository and completely missed this issue. Sorry for my late response!

**Comment by KeenVox** [comment]
> Hi,
> 
> What version of GCC are you using? I noticed that the newer versions produce significantly larger binaries. The performance seems to be a bit worse too. For this reason I stick with older compiler versions when compiling the usynth code. Last time I checked, GCC 10.1.0 seemed to be good enough. By the way, you can find precompiled binaries [here](https://github.com/Jacajack/usynth/tree/master/bin).
> 
> Optimizing the code for size is obviously a good workaround to get the code into the flash, but you may find the performance unsatisfactory. It's not bound to happen, of course, but is likely. When that happens, the sound appears distorted in a distinctive manner. You might miss it at first, but once you hear the clean version it becomes obvious.
> 
> The way I debugged performance issues in the code is actually very simple. MIDI controller 111 controls "profiling" of a certain load balancing channel (one of the 21 paths of execution in the main switch statement). If there's still some time left after generating the sample, the green LED will light up. Brightness of the LED tells you how much spare time you have in each branch. When the LED is visibly flickering, it usually means that this branch is overloaded and some artifacts may be audible.
> 
> I have no idea how this happened, but somehow I have unsubscribed from the notifications from this repository and completely missed this issue. Sorry for my late response!

Hey,
thanks for your reply. I didn't even check out that there were precompiled binaries. ^^ Will try those, in the moment it truly sounds a bit distorted.
I used the newest version of GCC through apt-get.
May really be the problem.

**Comment by KeenVox** [comment]
Hm, I did try the prebuild binarys but now nothing works. :-( I used avrdude with an usbasp.

**Comment by Jacajack** [comment]
That's interesting. Do you have your fuses and crystal set up properly?

**Comment by KeenVox** [comment]
I think so. I installed a 20Mhz crystal with two 22pf capacitors and set the fuses to external low freq crystal and disabled the "divded by 8" option.

**Comment by Jacajack** [comment]
Sounds good. Can you investigate whether the µC does anything at all or just doesn't respond to MIDI commands? UART problems are quite common, so it's worth ruling that out first. If you have access to an oscilloscope, you could look for look signs of life on the MOSI, SCK, OCR1A and OCR1B outputs. Does the size optimized version behave in the same way?

**Comment by KeenVox** [comment]
Will check the pins.
The size optimized version works normaly with midi commands etc. no problem there.
After flashing the 10.10 precompiled binary the first led lights up. After I resett the power, it stays off and doesn't react to any inputs.

**Comment by Jacajack** [comment]
Strange. In the meantime, I will double check the precompiled binaries again today.

**Comment by KeenVox** [comment]
I've checked the pins. I get nothing except on the rst pin, when I play some midi notes. 
With the size optimized version I get some activity on all pins.

**Comment by Jacajack** [comment]
That would mean that the precompiled version is not starting at all or crashing very quickly. I've just checked both ELF files and they work just fine on my µC. My chip is ATMEGA328U-TH, fuses are E:FF, H:D1, L:FF.  I have to admit, right now I'm out of ideas what could cause that.

Would you mind sharing the size optimized binary with me? I'll see if I can get it running on my chip.

**Comment by KeenVox** [comment]
I got it to work! Seemed to be a problem with the fuses after all. I used your settings an now it works.
Mine were E:FD and L:F7. 
And you are right, now the sound qualitiy is much better than before. :-)

**Comment by Jacajack** [comment]
Glad to hear that! I wonder whether this was caused by the brown-out detection or the different clock configuration. Anyway, I will put the my fuse bits values somewhere in the makefile or readme.
